language: rust
matrix:
  include:
    - os: linux
      rust: stable
      sudo: required
      dist: trusty
    - os: linux
      rust: nightly
      sudo: required
      dist: trusty
    - os: osx
      rust: stable
    - os: osx
      rust: nightly
install:
  # http://www.deb-multimedia.org/dists/unstable/main/binary-amd64/
  #
  # Linux part
  #
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libspeex1 libvo-amrwbenc0 libvpx1 libxvidcore4 libzvbi0 libva1 libgnutls-dev librtmp-dev libschroedinger-1.0 libopenjpeg-dev libopencore-amrwb0 libopencore-amrnb0 libgsm0710-0 libcrystalhd3 libvdpau1 libva-x11-1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://www.guillaume-gomez.fr/packages/ffmpeg-libs.deb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i ffmpeg-libs.deb ; fi
  #
  # OSX part
  #
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libvpx ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg --with-libvpx ; fi
  # libOpenCL libopus-dev libsoxr-dev
script:
  - rustc --version
  - RUST_BACKTRACE=1 cargo test
