environment:
  matrix:
    # Nightly channel
    - RUST: nightly
      BITS: 32
    - RUST: nightly
      BITS: 64

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - SET RUST_URL=https://static.rust-lang.org/dist/rust-%RUST%-%ARCH%-pc-windows-msvc.exe
  - SET PATH=C:\Rust\bin;C:\msys64\mingw%BITS%\bin;%PATH%;C:\msys64\usr\bin
  - ps: Start-FileDownload $Env:RUST_URL -FileName rust-dist.exe
  - rust-dist.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - 7z e package/win%BITS%.zip -o"C:\Program Files (x86)\ffmpeg" -y
  - SET PATH=%PATH%;"C:\Program Files (x86)\ffmpeg\win%BITS%\libs"
  - SET INCLUDE=%INCLUDE%;"C:\Program Files (x86)\ffmpeg\win%BITS%\include"
  - rustc -V
  - cargo -V

build: false

test_script:
  - rustc --version
  - cargo test
